export const lang = {
  lang: "en",
  en: {
    welcome_1: "Healthy",
    welcome_2: "Delicious",
    welcome_3: "Fresh",
    welcome_4: "Contact us",
    welcome_button: "Let's go",
    welcome_browse_menu: "Browse Menu",
    welcome_browse_packages: "Browse Packages",
    login_1: "Change password",
    login_2: "Enter Mobile Phone",
    login_3: "Send OTP >>",
    login_4: "Mobile Verification",
    login_5: "We have sent you an access code via SMS for mobile",
    login_6: "number verification: ",
    login_7: "Didn't recieve OTP?",
    login_8: "Resend",
    login_9: "Password",
    login_10: "Confirm Password",
    login_11: "Reset Password",
    login_12: "Mobile Phone",
    login_13: "Password",
    login_14: "Forgot password?",
    login_15: "Sign in",
    login_16: "New to swing?",
    login_17: "Create account",
    register_1: "Confirm",
    register_2: "Name",
    register_3: "Mobile Phone",
    register_4: "Email (optional)",
    register_5: "Date of birth (optional) \n",
    register_alert_6: "Please fill the required fields",
    register_alert_7: "Please enter a valid email address",
    register_alert_8: "Mobile number must be 8 numbers",
    register_9: "Next >>",
    register_10: "Already have account?",
    register_11: "Sign in",
    register_12: "Mobile Verification",
    register_13: "We have sent you an access code via SMS for mobile",
    register_14: "number verification: ",
    register_15: "Didn't recieve OTP?",
    register_alert_16: "Please enter a valid OTP number",
    register_17: "Change Number",
    register_18: "Password",
    register_19: "Confirm Password",
    register_20:
      "I agree to the terms & conditions of Swing Healthy Food subscribtions and orders delivery application.",
    register_21: "Verify",
    register_22: "Register",
    how_it_works_1: "How it works",
    how_it_works_2: "Complete your profile",
    how_it_works_3: "Start your subscription",
    how_it_works_4: "Pick your daily meals",
    how_it_works_5: "Let's go",
    complete_profile_1: "Complete your profile",
    complete_profile_2: "cm",
    complete_profile_3: "Height",
    complete_profile_4: "kg",
    complete_profile_5: "Weight",
    complete_profile_6: "Save",
    complete_residence_1: "Complete your address",
    complete_residence_2: "*Government",
    complete_residence_3: "Select a government",
    complete_residence_4: "*Area",
    complete_residence_5: "Select an area",
    complete_residence_6: "Notes",
    complete_residence_7: "*Block",
    complete_residence_8: "*Building",
    complete_residence_9: "Jadda",
    complete_residence_10: "*Street",
    complete_residence_11: "*Flat",
    complete_residence_12: "*Floor",
    complete_residence_13: "Register",
    complete_residence_14: "Choose government first",
    complete_residence_alert_15: "Please enter the required fields",
    add_diet_details_1: "Cancel",
    add_diet_details_2: "Diet details",
    add_diet_details_3: "*Diet type",
    add_diet_details_4: "Select your goal",
    add_diet_details_5: "Dislikes",
    add_diet_details_6: "Select an item",
    add_diet_details_7: "Allergies",
    add_diet_details_8: "Select an item",
    add_diet_details_9: "Off days",
    Saturday: "Saturday",
    Sunday: "Sunday",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    add_diet_details_10: "Add details",
    add_diet_details_alert_11: "Please enter the required fields",
    subscription_1: "back",
    package_selection_1: "Pick your subscription",
    package_selection_2: "Choose period",
    package_selection_3: "Choose subscription start date",
    package_selection_4: "# of Meals",
    package_selection_5: "# of Snacks",
    package_selection_6: "Show packages",
    package_selection_alert_7: "Please select number of meals",
    package_selection_alert_8: "Please select number of snacks",
    package_selection_alert_9: "Please select your subscription period",
    package_selection_alert_10: "Please select your subscription start date",
    available_package_1: "Choose a package",
    available_package_2: " Meals\n",
    available_package_3: " Meals",
    available_package_4: "\ndays",
    available_package_5: " KWD",
    available_package_6: "Pay",
    available_package_alert_7: "Please choose package first",
    payment_1: "Subscription Period",
    payment_2: " Days",
    payment_3: "Edit",
    payment_4: "Total Payment",
    payment_5: "kwd",
    payment_6: " Apply Promo Code",
    payment_7: "ُEnter Promo Code",
    payment_8: "ُApply",
    payment_9: "This promo code is not valid",
    payment_10: "Promo code applied succesfully! With Discount ",
    payment_11: "Choose your payment",
    payment_12: "Knet Payment",
    payment_13: "Credit/Debit Card",
    payment_14: "Checkout",
    payment_15: "Cancel",
    payment_16: "Payment completed successfully",
    payment_17: "let's choose your meals",
    payment_18: "Payment failed\nPlease try again",
    payment_19: "Try again",
    calendar_1: " Days",
    calendar_2: "Freeze Days",
    calendar_3: "Choose a day to pick your meals",
    calendar_4: " Active without Meals ",
    calendar_5: " Posted ",
    calendar_6: " Paused ",
    calendar_7: " Active With Meals ",
    calendar_alert_8: "Please defreeze this day first",
    calendar_alert_9: "This is a posted day you can't edit meals",
    freeze_1: "freeze/defreeze a day",
    freeze_2: " Days",
    freeze_3: " freezed days     ",
    freeze_4: "Save",
    add_meals_1:
      "You can't edit the meals on this day, \nthe meals have been posted.",
    add_meals_2: "<< Calendar",
    add_meals_3: "Save >>",
    add_meals_4: "Kcal",
    add_meals_5: "Protein",
    add_meals_6: "Fats",
    add_meals_7: "Carbs",
    add_meals_8: "Spicy",
    add_meals_9: "High Calories",
    add_meals_10: "Calories",
    add_meals_11: "Wonders Of The Dish",
    add_meals_12: "Heating Instructions",
    add_meals_13: "Nutritional Ingredients",
    personal_profile_1: "Edit Addresses",
    personal_profile_2: "Package & Subscription",
    personal_profile_3: "Allergies & Dislikes",
    personal_profile_4: "Delete account",
    personal_profile_5:
      "By deleting your account your subscribtions will be lost and all of your acount data will be deleted, and can not be restored againg",
    personal_profile_6: "Cancel",
    personal_profile_7: "Delete profile",
    personal_profile_8: "Warning!",
    personal_profile_9:
      "Are you sure that you want to permenently delete your account?",
    personal_profile_10: "yes, delete now",
    personal_profile_11: "no",
    edit_profile_1: "Add new address",
    edit_profile_2: "*Delivery Days",
    edit_profile_3: "*Delivery Time",
    edit_profile_4: "*Government",
    edit_profile_5: "*Area",
    edit_profile_6: "Choose government first",
    edit_profile_7: "Next",
    edit_profile_8: "*Address Name",
    edit_profile_9: "Add",
    edit_profile_10: "Addresses",
    edit_profile_11: "Delivery Days: \n",
    edit_profile_12: "\nDelivery Time: \n",
    edit_profile_13: "From: ",
    edit_profile_14: "\n To: ",
    edit_profile_15: "Area: ",
    edit_profile_16: "Notes: ",
    edit_profile_17: "Block: ",
    edit_profile_18: "Building: ",
    edit_profile_19: "Jadda: ",
    edit_profile_20: "Street: ",
    edit_profile_21: "Flat: ",
    edit_profile_22: "Floor: ",
    edit_profile_23: "delete",
    edit_profile_24: "edit",
    edit_profile_25: "Edit address",
    edit_profile_26: "Edit ",
    edit_profile_27: " address ",
    edit_profile_alert_28: "ُError",
    edit_profile_alert_29: "Can't delete your only address",
    edit_profile_alert_30: "Add address",
    edit_profile_alert_31: "Address ",
    edit_profile_alert_32: " added successfully.",
    edit_profile_alert_33: "Delete",
    edit_profile_alert_34: "Are you sure you want to delete address ",
    edit_profile_alert_35: "Cancel",
    edit_profile_alert_36: "OK",
    subscription_data_1: "Back",
    subscription_data_2: " Active Packages",
    subscription_data_3: "Start Date: ",
    subscription_data_4: "End Date: ",
    subscription_data_5: "No Current Active Packages",
    subscription_data_6: "Renew Subscription",
    subscription_data_7: "Add New Subscription",
    subscription_data_8: " Choose renewal process",
    subscription_data_9: "Fast Renewal",
    subscription_data_10:
      "-By choosing fast renewal the same existing last package will be choosen for the renewal process, you will only choose the new start date.",
    subscription_data_11: "New subscription",
    subscription_data_12:
      "-By choosing new subscription process you will choose a new subscription packages with new diet goals, period, contents and price.",
    subscription_data_13: "ٌRenew",
    subscription_data_14:
      "ٌNo current subscription data to use fast renewal process",
    subscription_data_15: "Please choose only one renewal process",
    subscription_data_16: "Please choose renewal process type",
    subscription_data_17: " Pick your start date",
    subscription_data_18: "Renew and Pay",
    subscription_data_19: "Remaining days",
    subscription_data_20: " Days",
    subscription_data_21: "Total price",
    subscription_data_22: "kwd",
    subscription_data_23: "Subscription Period: ",
    subscription_data_24: "Package Name: ",
    subscription_data_25: "Subscription start date: ",
    subscription_data_26: "Subscription end date: ",
    subscription_data_27: "Package content:  ",
    subscription_data_28: " Meals, ",
    subscription_data_29: " Snacks",
    subscription_data_30: "Renew Subscription",
    subscription_data_31: "Add New Subscription",
    allergies_dislikes_1: "Dislikes & Allergies",
    allergies_dislikes_2: "Dislikes: ",
    allergies_dislikes_3: " Allergies: ",
    allergies_dislikes_alert_4: "Dislikes and Allergies are added successfully",
    logout: "logout",
    yourPackage: "Your Package",
    numberOfDays: "Number of days",
    callorie: "callorie",
    fat: "fat",
    protine: "protine",
    carb: "carb",
    priceK: "Price (KWD)",
    
    selectGender: "Select Gender",
    male: "Male",
    female: "Female",
    selectHeight: "Select Height",
    selectWeight: "Select Weight",
    yourPackage: "Your Package",
    reviewPay: "Review & Pay",
    paymentSuccess: "Payment Success",
    payment: "Payment",
    createPassword: "Create Password",
    choosePaymentMethod: "Please choose payment method",
    chooseOnlyOnePaymentMethod: "Please choose only one payment method",
    paymentProcessingCheckPackges: "Payment is processing check your packges ",
    somethingWentWrong: "Something went wrong",
    chooseGender: "Please choose a gender!",
    registeredSuccessfully: "You registered successfully!",
    completeMealsFirst: "Please complete your meals first \n",
    selectSubscriptionStartDate: "Please select your subscription start date",
    errorLoadingPackages: "Error loading packages",
    errorLoadingMenu: "Error loading menu",
    enterOTPNumber: "Please enter a valid OTP number!",
    cantVerifyOtp: "Can't verify otp",
    changedSuccessfully: "Password Changed Successfully",
    cantTesetPasswordTryAgain: "Can't reset password please try again!",
    didntMatchTryAgain: "Password didn't match, Please try again!",
    passwordMustGreaterThan8Characters: "Password must be greater than 8 characters!",
    loginFailed: "Login Failed",
    checkLoginDataAndTryAgain: "Please check login data and try again!",
    cantSendOTPTryAgain: "Can't Send OTP to this mobile number, Please try again!",
    passwordDidntMatchTryAgain: "Password didn't match, Please try again!",
    passwordMustGreaterThan8Characters: "Password must be greater than 8 characters!",
    pleaseAgreeTermsConditions: "Please agree on the terms and conditions!",
    cantSendOTPTryAgain2: "Can't Send OTP to this mobile number, Please try again!",
    registerationFailed: "Registeration Failed",
    mobileAlreadyUse: "This Mobile number already in use",
    somethingWentWrong: "Something went wrong ",
    tryAgainLater: "Please try again later",
    error: "Error",
  },
  ar: {
    welcome_1: "صحي",
    welcome_2: "لذيذ",
    welcome_3: "طازج",
    welcome_4: "تواصل معنا",
    welcome_button: "هيا نبدأ",
    welcome_browse_menu: "تصفح القائمة",
    welcome_browse_packages: "تصفح الحزم",
    login_1: "تغيير كلمة المرور",
    login_2: "ادخل رقم الجوال",
    login_3: " << ارسل كود التفعيل",
    login_4: "التحقق من الجوال",
    login_5: "لقد ارسلنا لك رمز التفعيل عن طريق الSMS",
    login_6: "رمز التحقق: ",
    login_7: "لم يصلك الرمز؟",
    login_8: "اعد الارسال",
    login_9: "كلمة المرور",
    login_10: "تأكيد كلمة المرور",
    login_11: "تأكيد كلمة المرور الجديدة",
    login_12: "رقم الجوال",
    login_13: "كلمة المرور",
    login_14: "نسيت كلمة المرور؟",
    login_15: "تسجيل الدخول",
    login_16: "مستخدم جديد؟",
    login_17: "انشاء حساب",
    register_1: "تأكيد",
    register_2: "الاسم",
    register_3: "رقم الجوال",
    register_4: "البريد الالكتروني (اختياري)",
    register_5: "تاريخ الميلاد (اختياري) \n",
    register_alert_6: "الرجاء ادخال البيانات المطلوبة",
    register_alert_7: "الرجاء ادخال بريد الكتروني بشكل صحيح",
    register_alert_8: "يجب ان يحتوي رقم الجوال على 8 ارقام",
    register_9: "<< التالي",
    register_10: "لديك حساب بالفعل؟",
    register_11: "تسجيل الدخول",
    register_12: "التحقق من الجوال",
    register_13: "لقد ارسلنا لك رمز التفعيل عن طريق الSMS",
    register_14: "رمز التحقق: ",
    register_15: "لم يصلك الرمز؟",
    register_alert_16: "الرجاء ادخال رمز تفعيل صحيح",
    register_17: "تغيير الرقم",
    register_18: "كلمة المرور",
    register_19: "تأكيد كلمة المرور",
    register_20:
      "أوافق على شروط وأحكام اشتراكات swing \nللأغذية الصحية وتطبيق توصيل الطلبات.",
    register_21: "تأكيد",
    register_22: "تسجيل",
    how_it_works_1: "كيفية الاستخدام",
    how_it_works_2: "أكمل بياناتك الشخصية",
    how_it_works_3: "ابدأ بتسجيل اشتراكك",
    how_it_works_4: "اختر وجباتك اليومية",
    how_it_works_5: "هيا نبدأ",
    complete_profile_1: "أكمل بياناتك الشخصية",
    complete_profile_2: "سم",
    complete_profile_3: "الطول",
    complete_profile_4: "كج",
    complete_profile_5: "الوزن",
    complete_profile_6: "حفظ",
    complete_residence_1: "ادخل بيانات العنوان",
    complete_residence_2: "*المحافظة",
    complete_residence_3: "اختر محافظة",
    complete_residence_4: "*المنطقة",
    complete_residence_5: "اختر منطقة",
    complete_residence_6: "الملاحظات",
    complete_residence_7: "*قطعة",
    complete_residence_8: "*مبنى",
    complete_residence_9: "جادة",
    complete_residence_10: "*شارع",
    complete_residence_11: "*شقة",
    complete_residence_12: "*الطابق",
    complete_residence_13: "حفظ",
    complete_residence_14: "اختر محافظة اولا",
    complete_residence_alert_15: "الرجاء ادخال البيانات المطلوبة",
    add_diet_details_1: "الغاء",
    add_diet_details_2: "النظام الغذائي",
    add_diet_details_3: "*نوع النظام",
    add_diet_details_4: "اختر هدفك",
    add_diet_details_5: "طعام لا يعجبك",
    add_diet_details_6: "اختر طعام",
    add_diet_details_7: "طعام يسبب حساسية",
    add_diet_details_8: "اختر طعام",
    add_diet_details_9: "لا تريد استقبال الوجبات في ايام",
    Saturday: "السبت",
    Sunday: "الاحد",
    Monday: "الاثنين",
    Tuesday: "الثلاثاء",
    Wednesday: "الاربعاء",
    Thursday: "الخميس",
    Friday: "الجمعة",
    add_diet_details_10: "حفظ البيانات",
    add_diet_details_alert_11: "الرجاء ادخال البيانات المطلوبة",
    subscription_1: "الرجوع",
    package_selection_1: "ادخل بيانات الاشتراك",
    package_selection_2: "اختر مدة الاشتراك",
    package_selection_3: "اختر اول يوم في الاشتراك",
    package_selection_4: "عدد الوجبات",
    package_selection_5: "عدد السناك",
    package_selection_6: "اظهار الباقات",
    package_selection_alert_7: "بالرجاء ادخال عدد الوجبات",
    package_selection_alert_8: "بالرجاء اختيار عدد السناك",
    package_selection_alert_9: "بالرجاء اختيار مدة الاشتراك",
    package_selection_alert_10: "بالرجاء اختيار اول يوم في الاشتراك",
    available_package_1: "اختر باقة",
    available_package_2: " وجبات\n",
    available_package_3: " سناكات",
    available_package_4: "\nيوم",
    available_package_5: " دينار ",
    available_package_6: "دفع",
    available_package_alert_7: "بالرجاء اختيار الباقة",
    payment_1: "مدة الاشتراك",
    payment_2: " يوم",
    payment_3: "تعديل",
    payment_4: "المبلغ الكلي",
    payment_5: "دينار",
    payment_6: " تطبيق رمز الخصم",
    payment_7: "ُادخل رمز الخصم",
    payment_8: "ُتفعيل",
    payment_9: "هذا الرمز غير صالح",
    payment_10: "تم تفعيل رمز الخصم بنجاح! بنسبة ",
    payment_11: "اختر طريقة الدفع",
    payment_12: "الدفع عن طريق كي نت knet",
    payment_13: "بطاقة الائتمان او المدين",
    payment_14: "الدفع",
    payment_15: "الغاء",
    payment_16: "تم الدفع بنجاح",
    payment_17: "هيا نبدأ باختيار وجباتك",
    payment_18: "فشلت محاولة الدفع\nبالرجاء اعادة المحاولة",
    payment_19: "اعادة المحاولة",
    calendar_1: " يوم",
    calendar_2: "تجميد ايام الاشتراك",
    calendar_3: "اختر يوم لاختيار وجباتك",
    calendar_4: " متاح بدون وجبات ",
    calendar_5: " تم تأكيد الوجبات ",
    calendar_6: " مجمد ",
    calendar_7: " تم تسجيل الوجبات ",
    calendar_alert_8: "بالرجاء قم بفك تجميد هذا اليوم اولا",
    calendar_alert_9: "لقد تم تأكيد الطلب لهذا اليوم لا يمكن تغييره",
    freeze_1: "اختر يوم ليتم تجميده/تحريره",
    freeze_2: " يوم",
    freeze_3: " ايام مجمدة     ",
    freeze_4: "حفظ",
    add_meals_1: "لا يمكن تغيير طلبات هذا اليوم \nلقد تم تأكيد الطلبات",
    add_meals_2: "الايام >>",
    add_meals_3: "<< حفظ",
    add_meals_4: "سعرة\nحرارية",
    add_meals_5: "بروتين",
    add_meals_6: "دهون",
    add_meals_7: "كاربوهيدرات",
    add_meals_8: "حار",
    add_meals_9: "سعرات حرارية عالية",
    add_meals_10: "سعرات حرارية",
    add_meals_11: "اسرار هذا الطبق",
    add_meals_12: "تعليمات التسخين",
    add_meals_13: "العناصر الغذائية",
    personal_profile_1: "ادارة العناوين",
    personal_profile_2: "الباقات و الاشتراكات",
    personal_profile_3: "وجبات لا تعجبك/تسبب حساسية",
    personal_profile_4: "حذف الحساب",
    personal_profile_5:
      "عند حذف الحساب سيتم حذف جميع الباقات الخاصه بك ولن يمكن استعادتها وسيتم حذف جميع المعلومات الخاصه بك",
    personal_profile_6: "الغاء",
    personal_profile_7: "حذف الحساب",
    personal_profile_8: "!تحذير",
    personal_profile_9: "هل انت متأكد من حذف الحساب الخاص بك؟",
    personal_profile_10: "نعم احذف الان",
    personal_profile_11: "لا",
    edit_profile_1: "اضافة عنوان جديد",
    edit_profile_2: "*ايام التوصيل",
    edit_profile_3: "*وقت التوصيل",
    edit_profile_4: "*المحافظة",
    edit_profile_5: "*المنطقة",
    edit_profile_6: "اختر المحافظة اولا",
    edit_profile_7: "التالي",
    edit_profile_8: "*اسم العنوان",
    edit_profile_9: "اضافة",
    edit_profile_10: "العناوين",
    edit_profile_11: "ايام التوصيل: \n",
    edit_profile_12: "\nوقت التوصيل: \n",
    edit_profile_13: "من: ",
    edit_profile_14: "\n الى: ",
    edit_profile_15: "منطقة: ",
    edit_profile_16: "الملاحظات: ",
    edit_profile_17: "قطعة: ",
    edit_profile_18: "مبنى: ",
    edit_profile_19: "جادة: ",
    edit_profile_20: "شارع: ",
    edit_profile_21: "شقة: ",
    edit_profile_22: "طابق: ",
    edit_profile_23: "حذف",
    edit_profile_24: "تعديل",
    edit_profile_25: "تعديل العنوان",
    edit_profile_26: "ُتعديل ",
    edit_profile_27: " العنوان ",
    edit_profile_alert_28: "خطأ",
    edit_profile_alert_29: "لا يمكن مسح عنوانك الوحيد",
    edit_profile_alert_30: "اضافة عنوان",
    edit_profile_alert_31: "عنوان ",
    edit_profile_alert_32: " تم الاضافة بالنجاح.",
    edit_profile_alert_33: "حذف",
    edit_profile_alert_34: "هل انت متأكد انك تريد حذف ",
    edit_profile_alert_35: "الغاء",
    edit_profile_alert_36: "تأكيد",
    subscription_data_1: "الرجوع",
    subscription_data_2: " الباقات الحالية",
    subscription_data_3: "تاريخ البداية: ",
    subscription_data_4: "تاريخ النهاية: ",
    subscription_data_5: "لا يوجد باقات حالية",
    subscription_data_6: "تجديد الاشتراك",
    subscription_data_7: "اضافة اشتراك جديد",
    subscription_data_8: " اختر طريقة التجديد",
    subscription_data_9: "تجديد سريع",
    subscription_data_10:
      "-باختيار التجديد السريع ، سيتم اختيار نفس الباقة الأخيرة الحالية لعملية التجديد ، وسوف تختار فقط تاريخ البدء الجديد.",
    subscription_data_11: "اشتراك جديد",
    subscription_data_12:
      "-باختيار عملية اشتراك جديدة ، ستختار باقات اشتراك جديدة بأهداف نظام غذائي جديد ومدة ومحتويات وسعر.",
    subscription_data_13: "ٌتجديد",
    subscription_data_14:
      "ٌلا يوجد بيانات اشتراك حالية لاستخدام التجديد السريع",
    subscription_data_15: "بالرجاء اختيار طريقة تجديد واحدة",
    subscription_data_16: "بالرجاء اختيار طريقة دفع ",
    subscription_data_17: " اختر اليوم الاول",
    subscription_data_18: "التجديد و الدفع",
    subscription_data_19: "الايام المتبقية",
    subscription_data_20: " يوم",
    subscription_data_21: "السعر الكلي",
    subscription_data_22: "دينار",
    subscription_data_23: "فترة الاشتراك: ",
    subscription_data_24: "اسم الباقة: ",
    subscription_data_25: "تاريخ بداية : ",
    subscription_data_26: "تاريخ الانتهاء : ",
    subscription_data_27: "محتويات الباقة : ",
    subscription_data_28: " الوجبات, ",
    subscription_data_29: " سناك",
    subscription_data_30: "تجديد الاشتراك",
    subscription_data_31: "اضافة اشتراك جديد",
    allergies_dislikes_1: "وجبات لا تعجبك/تسبب حساسية",
    allergies_dislikes_2: "وجبات لا تعجبك ",
    allergies_dislikes_3: " وجبات تسبب حساسية ",
    allergies_dislikes_alert_4: "تمت الاضافة بنجاح",
    logout: "تسجيل الخروج",

    yourPackage: "اشتراكك",
    numberOfDays: "رقم اليوم",
    priceK: "السعر د.ك",
    callorie: "سعرات",
    fat: "دهون",
    protine: "بروتين",
    carb: "كارب",
    priceK: "السعر د.ك",

    selectGender: "اختر الجنس",
    male: "ذكر",
    female: "أنثى",
    selectHeight: "اختر الطول",
    selectWeight: "اختر الوزن",
    yourPackage: "باقتك",
    reviewPay: "المراجعة والدفع",
    paymentSuccess: "نجاح الدفع",
    payment: "الدفع",
    createPassword: "إنشاء كلمة المرور",
    choosePaymentMethod: "الرجاء اختيار طريقة الدفع",
    chooseOnlyOnePaymentMethod: "يرجى اختيار طريقة دفع واحدة فقط",
    paymentProcessingCheckPackges: "جاري معالجة الدفع للتحقق من الطرود الخاصة بك",
    somethingWentWrong: "حدث خطأ ما",
    chooseGender: "الرجاء اختيار الجنس!",
    registeredSuccessfully: "لقد قمت بالتسجيل بنجاح!",
    completeMealsFirst: "من فضلك أكمل وجباتك أولاً \n",
    selectSubscriptionStartDate: "الرجاء تحديد تاريخ بدء الاشتراك",
    errorLoadingPackages: "خطأ في تحميل الباقات",
    errorLoadingMenu: "خطأ في تحميل القائمة",
    enterOTPNumber: "الرجاء إدخال رقم OTP صالح!",
    cantVerifyOtp: "لا يمكن التحقق من OTP",
    changedSuccessfully: "تم تغيير كلمة المرور بنجاح",
    cantTesetPasswordTryAgain: "لا يمكن إعادة تعيين كلمة المرور يرجى المحاولة مرة أخرى!",
    didntMatchTryAgain: "كلمة المرور غير متطابقة، يرجى المحاولة مرة أخرى!",
    passwordMustGreaterThan8Characters: "كلمة المرور يجب أن تكون أكبر من 8 أحرف!",
    loginFailed: "فشل تسجيل الدخول",
    checkLoginDataAndTryAgain: "الرجاء التحقق من بيانات تسجيل الدخول والمحاولة مرة أخرى!",
    cantSendOTPTryAgain:
      "لا يمكن إرسال كلمة المرور لمرة واحدة (OTP) إلى رقم الهاتف المحمول هذا، يرجى المحاولة مرة أخرى!",
    passwordDidntMatchTryAgain: "كلمة المرور غير متطابقة، يرجى المحاولة مرة أخرى!",
    passwordMustGreaterThan8Characters: "كلمة المرور يجب أن تكون أكبر من 8 أحرف!",
    pleaseAgreeTermsConditions: "يرجى الموافقة على الشروط والأحكام!",
    cantSendOTPTryAgain2:
      "لا يمكن إرسال كلمة المرور لمرة واحدة (OTP) إلى رقم الهاتف المحمول هذا، يرجى المحاولة مرة أخرى!",
    registerationFailed: "فشل التسجيل",
    mobileAlreadyUse: "رقم الجوال هذا قيد الاستخدام بالفعل",
    somethingWentWrong: "حدث خطأ ما ",
    tryAgainLater: "الرجاء المحاولة مرة أخرى في وقت لاحق",
    error: "خطأ",
    done: "تم",
  },
};
